### PR TITLE
Fixed Broken Link and Fixed up Markdown Structure.

### PR DESCRIPTION
**Pull request by mendelsphotography**
Fixed Broken Link for the project had An "S"  and Fixed up Markdown Structure To Be More Readable.

### CODE REVIEW

**Review by mendelgordon — APPROVED** [review]
Good catch!

**Comment by mendelsphotography** [comment]
you can Also add 
image to the About section since it did not go with my pull request

**Comment by mendelsphotography** [comment]
@mendelgordon Just saying it seems all Your Projects don't have readme's And you should really add one to each project you make since let's say someone comes to your profile and sees your projects but have no idea what it does... and Btw if you also did not know about [netlify](https://www.netlify.com/)  wich is free hosting and GitHub repo's

**Comment by mendelgordon** [comment]
Thanks for pointing that out, I went ahead and added a readme to each project!
I also started using netlify, which happened to be the very next part of the codecademy course I'm taking now 😄

**Comment by mendelsphotography** [comment]
So it looks like you are new to coding. I assumed you did coding for a while as I see you work for chabad.org And assumed they don't take people without real good coding skills. 
not that I am. Still learning stopped and restarting now again while trying to do UX/UI and photography and more.

**Pull request merged**
